### ISSUE TITLE
ピアノ会場が壊せてしまう。

### ISSUE THREAD

**Issue by mametoufu0311** [BulletProject/bug-tracker#2]
ピアノ会場の中とその入り口の
トラップドアの一個下までが、自由に
ものを置いたり、壊したりが可能に
なっていました。
のりまきさんに入れないよう、
直してもらったのですが、
リスタートする毎に戻ってしまうので、
みんなが脱走しまくっています。
修正お願い致します。

**Comment by mametoufu0311** [comment]
それと何故か、半ブロックと階段に
はまったり、それらの上を歩いた時に
ロールバックしてしまいます。
味方と敵がﾜｧｰと来ている時にはまって
動けなくなり、視点も何故か固定され、
フルボッコにされてしまいます。
それと時々弾が出なくなります。
リロード中でも弾切れでもない時です。
しかも相手に当たりません。
ですが弾数は減ります。
OSはios9.3 未脱獄 テクスチャ変更無し
minecraftのversionは1.5.6です。
iPod touch 5です。
チャット開くだけでカクつくため、
simejiなどは使っていません。

**Comment by mametoufu0311** [comment]
それと銃が近すぎると当たりません。
殴ったと後認知されてダメージ
消されているんでしょうか
それを修正して欲しいです。
それとアイテムを持った時に
銃の名前のと一緒に、弾数も表示するように
して欲しいです。確認する際に
一度発車しないといけないため、
弾をロストし、打ち負けしやすくなってしまいます

**Comment by mametoufu0311** [comment]
お願い致します

**Comment by haniokasai** [comment]
バグを1つずつ別項目にして書き直してください
