### ISSUE TITLE
新しい武器や防具の追加

### ISSUE THREAD

**Issue by kyuubipensi** [BulletProject/bug-tracker#32]
提案です。
システム・ウェポン銃の追加 (例 普段はライフルだが、スニーク中は狙撃銃になる銃)
ペッパーボックスピストルの追加 (一回の引き金で2.3発の弾を発射するハンドガン)
馬の追加(拠点の中や横に数匹の馬)
アサルトライフルの追加(普段は弱めの機関銃だがスニーク中は強めのショットガン)
暗視ゴーグル装備の追加(金の頭装備１つ 能力は暗視)
光学迷彩装備の追加(金の足装備１つ 能力は透明化)
地雷の追加(TNT＋感圧版など)
煙幕弾の追加(盲目など)

**Comment by kyuubipensi** [comment]
１つにまとめてはダメでしたか？
余りにも多いので…

**Comment by haniokasai** [comment]
すべて1つずつにしてくれるとありがたいです。

**Comment by kyuubipensi** [comment]
わかりました。

**Comment by kyuubipensi** [comment]
どうやるんでしょうか

**Comment by haniokasai** [comment]
申し訳ありません、サーバーの更新を終了しました
